### ISSUE TITLE
Storing a date with a task

### ISSUE THREAD

**Issue by Qtipshooter** [Qtipshooter/taskbook-SWE#19]

**Comment by Qtipshooter** [comment]
Users should be able to add tasks freely and are currently able to, but users are unable to store a date with that at this time.  We need to modify it to do so

**Comment by Qtipshooter** [comment]
- [ ] Add date as a column for a task
- [ ] Remove list column for today/tomorrow
- [ ] change updates in code to reflect the changes to the database

**Comment by ShrutiGupta354** [comment]
What is the difference between this issue and the #16 Simple add feature - date and task name issue?
