### ISSUE TITLE
Have a navigation bar

### ISSUE THREAD

**Issue by sagarsubedi** [Qtipshooter/taskbook-SWE#43]
Currently, we do not have a navigation bar. That would be a poor UX choice. I do not know exactly how many screens/pages we will have but I think we need a nice looking navigation bar for better UX. For now, we just have a navbar with the app title that takes us to the home page. We need something better

**Comment by sagarsubedi** [comment]
@Qtipshooter Please have a look at this issue and assign it to me. I can work on this.

**Comment by Qtipshooter** [comment]
That's fine, go ahead.  Let Julianne know as well

**Comment by jelbin313** [comment]
We are basically using the buttons on the calendar, weekly, and tasks pages as a navbar, other than that, idk if one is necessary?
Navigation is necessary but I don't think we're doing it in the form of a bar.
