### ISSUE TITLE
View as day Backend

### ISSUE THREAD

**Issue by Qtipshooter** [Qtipshooter/taskbook-SWE#5]
View the taskbook as a particular day

**Comment by Qtipshooter** [comment]
My understanding of how we would do this would be along these lines:
When viewing a day, tasks that would classify as missed would not be shown
Everything from that day would be shown in today column
Everything past that would show in tomorrow (or if we do the week thing, in that area sorted based on current day)

**Comment by Roodude15** [comment]
Think of a way of doing the upcoming tasks, we need to come up with a good way to increment the date for collecting the next tasks
