### ISSUE TITLE
Today vs Upcoming Front End

### ISSUE THREAD

**Issue by jelbin313** [Qtipshooter/taskbook-SWE#6]
Feature that sorts between events/tasks scheduled for today and upcoming events/task in the next 7 days

**Comment by Qtipshooter** [comment]
I think we would be doing this based on the date that is stored with each task

**Comment by Qtipshooter** [comment]
We are doing this as a today vs next 10 task list regardless of day.  This will show the date of a task with it and sort them, but not group them
