### ISSUE TITLE
Automation of the web server

### ISSUE THREAD

**Issue by Roodude15** [Qtipshooter/taskbook-SWE#92]

**Comment by Qtipshooter** [comment]
Definitions of Done

- [ ] Make servers for both production and development main
- [ ] Get keys to ssh into these servers into the actions secrets
- [ ] Write a script to deploy the project to each server on the following actions
  - [ ] To production on push to branch [production]
  - [ ] To development on push to branch [main]
  - [ ] To server on workflow_dispatch on both of these
- [ ] Make sure that the script takes the following actions
  - [ ] Verify pip and python are installed/ install them if they are not
  - [ ] Verify that flask and dataset are installed with pip/ install them if they are not
  - [ ] Go to dedicated project directory
  - [ ] Remove Folder the project would go in (We will make a deploy that doesn't delete our current project at some point as well)
  - [ ] Clone project into the directory
  - [ ] Remove .git folder
- [ ] Create a dummy workflow that can be used for testing workflows (not the project itself, but sample workflows to see if they work for example)
